### ISSUE TITLE
好像不能完成课程评估

### ISSUE THREAD

**Issue by beckzhu** [chenqi191/21tb-study#1]
感谢作者提供这么强大大工具，有个问题系统作者能解决下，就是不能自动评估课程，当课程中有正在评估的课程，将会一直卡在那里

**Comment by chenqi191** [comment]
不太清楚你的问题，不过我的程序基本没考虑很多异常情况，就是一条路线走下去。这三个月，我用一直没有出问题，再加上工作比较忙，暂时不怎么想再更新了。之前碰到过的问题，有些课程是PPT，或者老视频用的老播放器，好像就会走不下去，我建议，浏览器登录，把已选的所有课程全部删掉，然后运行软件，他会自动获取课程学习的，再在系统计划任务里加入自动启动，这几个月，我就没再管过它，每天中午自己就打开学习了，也能正常获取学分

**Comment by pone** [comment]
确实是不能完成评估，如果有评估会一直卡在评估处。是不是api变了？

**Comment by chenqi191** [comment]
酱紫？这几天我看看，之前网络协议从http变成https，我找了好久才发现

**Comment by pone** [comment]
感谢大佬。求教大佬这个api接口可以从哪里找到

**Comment by chenqi191** [comment]
啊？ 你说api.conf里面的那些接口吗，我不知道有没有好方法，我就手动在浏览器开F12一步一步来回点，然后找确认接口是哪些

**Comment by pone** [comment]
目前貌似是卡在了选择题

**Comment by chenqi191** [comment]
我又提交了一次exe，不知道有没有改过什么，忘记了，我这三个月，都是在自动学习的，没操作过，每个月公司评比也都是排前列，你把所有选的课程都删掉试试，之前我也卡过，都删干净之后就没卡过了

过几天我再看看是不是哪里出了什么问题

**Comment by pone** [comment]
谢谢大佬

**Comment by pone** [comment]
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "study.py", line 448, in study
    item_list = self.get_course_item(course['id'])
  File "study.py", line 477, in get_course_item
    r = self.http.get(url)
  File "study.py", line 243, in get
    return r.json()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

目前部分课程会卡在 获取课程地址：#### python报上面的错误

**Comment by FJSEN** [comment]
大佬 nb 赞一个
